env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  explicit-module-boundary-types: off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-empty: error
  no-explicit-any: off
  quotes:
    - error
    - single
  semi:
    - error
    - never

