env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:prettier/recommended"
overrides:
  - files: "**/*.svelte"
    processor: "svelte3/svelte3"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  extraFileExtensions: ".svelte"
  project: "./tsconfig.lint.json"
  sourceType: module
  tsconfigRootDir: "./"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "svelte3"
rules:
  explicit-module-boundary-types: off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-empty: error
  no-explicit-any: off
  quotes:
    - error
    - single
  semi:
    - error
    - never
settings:
  "svelte3/typescript": true
