name: pr-checks

on:
  push:
    branches:
      - chore/**
      - fix/**
      - feat/**
      - hotfix/**

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        working-directory: packages/shared
        run: yarn

      - name: Test
        working-directory: packages/shared
        run: yarn test
